export interface CountryCode {
  code: string
  name: string
  dial_code: string
  format: string
}

export const countryCodes: CountryCode[] = [
  {
    code: "AF",
    name: "Afghanistan",
    dial_code: "+93",
    format: "XX XXX XXXX",
  },
  {
    code: "AL",
    name: "Albania",
    dial_code: "+355",
    format: "XX XXX XXXX",
  },
  {
    code: "DZ",
    name: "Algeria",
    dial_code: "+213",
    format: "XXX XX XX XX",
  },
  {
    code: "AS",
    name: "American Samoa",
    dial_code: "+1684",
    format: "XXX XXXX",
  },
  {
    code: "AD",
    name: "Andorra",
    dial_code: "+376",
    format: "XXX XXX",
  },
  {
    code: "AO",
    name: "Angola",
    dial_code: "+244",
    format: "XXX XXX XXX",
  },
  {
    code: "AI",
    name: "Anguilla",
    dial_code: "+1264",
    format: "XXX XXXX",
  },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    dial_code: "+1268",
    format: "XXX XXXX",
  },
  {
    code: "AR",
    name: "Argentina",
    dial_code: "+54",
    format: "XX XXXX XXXX",
  },
  {
    code: "AM",
    name: "Armenia",
    dial_code: "+374",
    format: "XX XXX XXX",
  },
  {
    code: "AW",
    name: "Aruba",
    dial_code: "+297",
    format: "XXX XXXX",
  },
  {
    code: "AU",
    name: "Australia",
    dial_code: "+61",
    format: "XXX XXX XXX",
  },
  {
    code: "AT",
    name: "Austria",
    dial_code: "+43",
    format: "XXX XXX XXXX",
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    dial_code: "+994",
    format: "XX XXX XXXX",
  },
  {
    code: "BS",
    name: "Bahamas",
    dial_code: "+1242",
    format: "XXX XXXX",
  },
  {
    code: "BH",
    name: "Bahrain",
    dial_code: "+973",
    format: "XXXX XXXX",
  },
  {
    code: "BD",
    name: "Bangladesh",
    dial_code: "+880",
    format: "XXXX XXXXXX",
  },
  {
    code: "BB",
    name: "Barbados",
    dial_code: "+1246",
    format: "XXX XXXX",
  },
  {
    code: "BY",
    name: "Belarus",
    dial_code: "+375",
    format: "XX XXX XXXX",
  },
  {
    code: "BE",
    name: "Belgium",
    dial_code: "+32",
    format: "XXX XX XX XX",
  },
  {
    code: "BZ",
    name: "Belize",
    dial_code: "+501",
    format: "XXX XXXX",
  },
  {
    code: "BJ",
    name: "Benin",
    dial_code: "+229",
    format: "XX XXX XXX",
  },
  {
    code: "BM",
    name: "Bermuda",
    dial_code: "+1441",
    format: "XXX XXXX",
  },
  {
    code: "BT",
    name: "Bhutan",
    dial_code: "+975",
    format: "XX XXX XXX",
  },
  {
    code: "BO",
    name: "Bolivia",
    dial_code: "+591",
    format: "X XXX XXXX",
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    dial_code: "+387",
    format: "XX XXX XXX",
  },
  {
    code: "BW",
    name: "Botswana",
    dial_code: "+267",
    format: "XX XXX XXX",
  },
  {
    code: "BR",
    name: "Brazil",
    dial_code: "+55",
    format: "XX XXXXX XXXX",
  },
  {
    code: "IO",
    name: "British Indian Ocean Territory",
    dial_code: "+246",
    format: "XXX XXXX",
  },
  {
    code: "BN",
    name: "Brunei Darussalam",
    dial_code: "+673",
    format: "XXX XXXX",
  },
  {
    code: "BG",
    name: "Bulgaria",
    dial_code: "+359",
    format: "XXX XXX XXX",
  },
  {
    code: "BF",
    name: "Burkina Faso",
    dial_code: "+226",
    format: "XX XX XX XX",
  },
  {
    code: "BI",
    name: "Burundi",
    dial_code: "+257",
    format: "XX XX XXXX",
  },
  {
    code: "KH",
    name: "Cambodia",
    dial_code: "+855",
    format: "XX XXX XXX",
  },
  {
    code: "CM",
    name: "Cameroon",
    dial_code: "+237",
    format: "XXXX XXXX",
  },
  {
    code: "CA",
    name: "Canada",
    dial_code: "+1",
    format: "XXX XXX XXXX",
  },
  {
    code: "CV",
    name: "Cape Verde",
    dial_code: "+238",
    format: "XXX XXXX",
  },
  {
    code: "KY",
    name: "Cayman Islands",
    dial_code: "+1345",
    format: "XXX XXXX",
  },
  {
    code: "CF",
    name: "Central African Republic",
    dial_code: "+236",
    format: "XX XX XX XX",
  },
  {
    code: "TD",
    name: "Chad",
    dial_code: "+235",
    format: "XX XX XX XX",
  },
  {
    code: "CL",
    name: "Chile",
    dial_code: "+56",
    format: "X XXXX XXXX",
  },
  {
    code: "CN",
    name: "China",
    dial_code: "+86",
    format: "XXX XXXX XXXX",
  },
  {
    code: "CX",
    name: "Christmas Island",
    dial_code: "+61",
    format: "XXX XXX XXX",
  },
  {
    code: "CC",
    name: "Cocos (Keeling) Islands",
    dial_code: "+61",
    format: "XXX XXX XXX",
  },
  {
    code: "CO",
    name: "Colombia",
    dial_code: "+57",
    format: "XXX XXX XXXX",
  },
  {
    code: "KM",
    name: "Comoros",
    dial_code: "+269",
    format: "XXX XXXX",
  },
  {
    code: "CG",
    name: "Congo",
    dial_code: "+242",
    format: "XX XXX XXXX",
  },
  {
    code: "CD",
    name: "Congo, Democratic Republic",
    dial_code: "+243",
    format: "XX XXX XXXX",
  },
  {
    code: "CK",
    name: "Cook Islands",
    dial_code: "+682",
    format: "XX XXX",
  },
  {
    code: "CR",
    name: "Costa Rica",
    dial_code: "+506",
    format: "XXXX XXXX",
  },
  {
    code: "CI",
    name: "Cote d'Ivoire",
    dial_code: "+225",
    format: "XX XXX XXX",
  },
  {
    code: "HR",
    name: "Croatia",
    dial_code: "+385",
    format: "XX XXX XXXX",
  },
  {
    code: "CU",
    name: "Cuba",
    dial_code: "+53",
    format: "X XXX XXXX",
  },
  {
    code: "CY",
    name: "Cyprus",
    dial_code: "+357",
    format: "XXXX XXXX",
  },
  {
    code: "CZ",
    name: "Czech Republic",
    dial_code: "+420",
    format: "XXX XXX XXX",
  },
  {
    code: "DK",
    name: "Denmark",
    dial_code: "+45",
    format: "XXXX XXXX",
  },
  {
    code: "DJ",
    name: "Djibouti",
    dial_code: "+253",
    format: "XX XX XX XX",
  },
  {
    code: "DM",
    name: "Dominica",
    dial_code: "+1767",
    format: "XXX XXXX",
  },
  {
    code: "DO",
    name: "Dominican Republic",
    dial_code: "+1",
    format: "XXX XXX XXXX",
  },
  {
    code: "EC",
    name: "Ecuador",
    dial_code: "+593",
    format: "XX XXX XXXX",
  },
  {
    code: "EG",
    name: "Egypt",
    dial_code: "+20",
    format: "XX XXXX XXXX",
  },
  {
    code: "SV",
    name: "El Salvador",
    dial_code: "+503",
    format: "XXXX XXXX",
  },
  {
    code: "GQ",
    name: "Equatorial Guinea",
    dial_code: "+240",
    format: "XXX XXX XXX",
  },
  {
    code: "ER",
    name: "Eritrea",
    dial_code: "+291",
    format: "X XXX XXX",
  },
  {
    code: "EE",
    name: "Estonia",
    dial_code: "+372",
    format: "XXXX XXXX",
  },
  {
    code: "ET",
    name: "Ethiopia",
    dial_code: "+251",
    format: "XX XXX XXXX",
  },
  {
    code: "FK",
    name: "Falkland Islands",
    dial_code: "+500",
    format: "XXXXX",
  },
  {
    code: "FO",
    name: "Faroe Islands",
    dial_code: "+298",
    format: "XXX XXX",
  },
  {
    code: "FJ",
    name: "Fiji",
    dial_code: "+679",
    format: "XXX XXXX",
  },
  {
    code: "FI",
    name: "Finland",
    dial_code: "+358",
    format: "XX XXX XXXX",
  },
  {
    code: "FR",
    name: "France",
    dial_code: "+33",
    format: "X XX XX XX XX",
  },
  {
    code: "GF",
    name: "French Guiana",
    dial_code: "+594",
    format: "XXX XX XX XX",
  },
  {
    code: "PF",
    name: "French Polynesia",
    dial_code: "+689",
    format: "XX XX XX XX",
  },
  {
    code: "GA",
    name: "Gabon",
    dial_code: "+241",
    format: "X XX XX XX",
  },
  {
    code: "GM",
    name: "Gambia",
    dial_code: "+220",
    format: "XXX XXXX",
  },
  {
    code: "GE",
    name: "Georgia",
    dial_code: "+995",
    format: "XXX XXX XXX",
  },
  {
    code: "DE",
    name: "Germany",
    dial_code: "+49",
    format: "XXXX XXXXXXX",
  },
  {
    code: "GH",
    name: "Ghana",
    dial_code: "+233",
    format: "XX XXX XXXX",
  },
  {
    code: "GI",
    name: "Gibraltar",
    dial_code: "+350",
    format: "XXXX XXXX",
  },
  {
    code: "GR",
    name: "Greece",
    dial_code: "+30",
    format: "XXX XXX XXXX",
  },
  {
    code: "GL",
    name: "Greenland",
    dial_code: "+299",
    format: "XX XX XX",
  },
  {
    code: "GD",
    name: "Grenada",
    dial_code: "+1473",
    format: "XXX XXXX",
  },
  {
    code: "GP",
    name: "Guadeloupe",
    dial_code: "+590",
    format: "XXX XX XX XX",
  },
  {
    code: "GU",
    name: "Guam",
    dial_code: "+1671",
    format: "XXX XXXX",
  },
  {
    code: "GT",
    name: "Guatemala",
    dial_code: "+502",
    format: "XXXX XXXX",
  },
  {
    code: "GN",
    name: "Guinea",
    dial_code: "+224",
    format: "XXX XXX XXX",
  },
  {
    code: "GW",
    name: "Guinea-Bissau",
    dial_code: "+245",
    format: "XXX XXXX",
  },
  {
    code: "GY",
    name: "Guyana",
    dial_code: "+592",
    format: "XXX XXXX",
  },
  {
    code: "HT",
    name: "Haiti",
    dial_code: "+509",
    format: "XXXX XXXX",
  },
  {
    code: "HN",
    name: "Honduras",
    dial_code: "+504",
    format: "XXXX XXXX",
  },
  {
    code: "HK",
    name: "Hong Kong",
    dial_code: "+852",
    format: "XXXX XXXX",
  },
  {
    code: "HU",
    name: "Hungary",
    dial_code: "+36",
    format: "XX XXX XXXX",
  },
  {
    code: "IS",
    name: "Iceland",
    dial_code: "+354",
    format: "XXX XXXX",
  },
  {
    code: "IN",
    name: "India",
    dial_code: "+91",
    format: "XXXXX XXXXX",
  },
  {
    code: "ID",
    name: "Indonesia",
    dial_code: "+62",
    format: "XXX XXX XXX",
  },
  {
    code: "IR",
    name: "Iran",
    dial_code: "+98",
    format: "XXX XXX XXXX",
  },
  {
    code: "IQ",
    name: "Iraq",
    dial_code: "+964",
    format: "XXX XXX XXXX",
  },
  {
    code: "IE",
    name: "Ireland",
    dial_code: "+353",
    format: "XX XXX XXXX",
  },
  {
    code: "IL",
    name: "Israel",
    dial_code: "+972",
    format: "XX XXX XXXX",
  },
  {
    code: "IT",
    name: "Italy",
    dial_code: "+39",
    format: "XXX XXX XXXX",
  },
  {
    code: "JM",
    name: "Jamaica",
    dial_code: "+1876",
    format: "XXX XXXX",
  },
  {
    code: "JP",
    name: "Japan",
    dial_code: "+81",
    format: "XX XXXX XXXX",
  },
  {
    code: "JO",
    name: "Jordan",
    dial_code: "+962",
    format: "X XXXX XXXX",
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    dial_code: "+7",
    format: "XXX XXX XXXX",
  },
  {
    code: "KE",
    name: "Kenya",
    dial_code: "+254",
    format: "XXX XXX XXX",
  },
  {
    code: "KI",
    name: "Kiribati",
    dial_code: "+686",
    format: "XXXXXX",
  },
  {
    code: "KP",
    name: "North Korea",
    dial_code: "+850",
    format: "XX XXX XXX",
  },
  {
    code: "KR",
    name: "South Korea",
    dial_code: "+82",
    format: "XX XXXX XXXX",
  },
  {
    code: "KW",
    name: "Kuwait",
    dial_code: "+965",
    format: "XXXX XXXX",
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    dial_code: "+996",
    format: "XXX XXX XXX",
  },
  {
    code: "LA",
    name: "Laos",
    dial_code: "+856",
    format: "XX XX XXX XXX",
  },
  {
    code: "LV",
    name: "Latvia",
    dial_code: "+371",
    format: "XXXX XXXX",
  },
  {
    code: "LB",
    name: "Lebanon",
    dial_code: "+961",
    format: "XX XXX XXX",
  },
  {
    code: "LS",
    name: "Lesotho",
    dial_code: "+266",
    format: "XXXX XXXX",
  },
  {
    code: "LR",
    name: "Liberia",
    dial_code: "+231",
    format: "XXX XXX XXX",
  },
  {
    code: "LY",
    name: "Libya",
    dial_code: "+218",
    format: "XX XXX XXXX",
  },
  {
    code: "LI",
    name: "Liechtenstein",
    dial_code: "+423",
    format: "XXX XXXX",
  },
  {
    code: "LT",
    name: "Lithuania",
    dial_code: "+370",
    format: "XXX XXXXX",
  },
  {
    code: "LU",
    name: "Luxembourg",
    dial_code: "+352",
    format: "XXX XXX XXX",
  },
  {
    code: "MO",
    name: "Macao",
    dial_code: "+853",
    format: "XXXX XXXX",
  },
  {
    code: "MK",
    name: "Macedonia",
    dial_code: "+389",
    format: "XX XXX XXX",
  },
  {
    code: "MG",
    name: "Madagascar",
    dial_code: "+261",
    format: "XX XX XXX XX",
  },
  {
    code: "MW",
    name: "Malawi",
    dial_code: "+265",
    format: "XXX XXX XXX",
  },
  {
    code: "MY",
    name: "Malaysia",
    dial_code: "+60",
    format: "XX XXXX XXXX",
  },
  {
    code: "MV",
    name: "Maldives",
    dial_code: "+960",
    format: "XXX XXXX",
  },
  {
    code: "ML",
    name: "Mali",
    dial_code: "+223",
    format: "XXXX XXXX",
  },
  {
    code: "MT",
    name: "Malta",
    dial_code: "+356",
    format: "XXXX XXXX",
  },
  {
    code: "MH",
    name: "Marshall Islands",
    dial_code: "+692",
    format: "XXX XXXX",
  },
  {
    code: "MQ",
    name: "Martinique",
    dial_code: "+596",
    format: "XXX XX XX XX",
  },
  {
    code: "MR",
    name: "Mauritania",
    dial_code: "+222",
    format: "XXXX XXXX",
  },
  {
    code: "MU",
    name: "Mauritius",
    dial_code: "+230",
    format: "XXXX XXXX",
  },
  {
    code: "YT",
    name: "Mayotte",
    dial_code: "+262",
    format: "XXX XX XX XX",
  },
  {
    code: "MX",
    name: "Mexico",
    dial_code: "+52",
    format: "XXX XXX XXXX",
  },
  {
    code: "FM",
    name: "Micronesia",
    dial_code: "+691",
    format: "XXX XXXX",
  },
  {
    code: "MD",
    name: "Moldova",
    dial_code: "+373",
    format: "XXXX XXXX",
  },
  {
    code: "MC",
    name: "Monaco",
    dial_code: "+377",
    format: "XXXX XXXX",
  },
  {
    code: "MN",
    name: "Mongolia",
    dial_code: "+976",
    format: "XXXX XXXX",
  },
  {
    code: "ME",
    name: "Montenegro",
    dial_code: "+382",
    format: "XX XXX XXX",
  },
  {
    code: "MS",
    name: "Montserrat",
    dial_code: "+1664",
    format: "XXX XXXX",
  },
  {
    code: "MA",
    name: "Morocco",
    dial_code: "+212",
    format: "XXXX XXXXX",
  },
  {
    code: "MZ",
    name: "Mozambique",
    dial_code: "+258",
    format: "XX XXX XXXX",
  },
  {
    code: "MM",
    name: "Myanmar",
    dial_code: "+95",
    format: "X XXX XXXX",
  },
  {
    code: "NA",
    name: "Namibia",
    dial_code: "+264",
    format: "XX XXX XXXX",
  },
  {
    code: "NR",
    name: "Nauru",
    dial_code: "+674",
    format: "XXX XXXX",
  },
  {
    code: "NP",
    name: "Nepal",
    dial_code: "+977",
    format: "XX XXXX XXXX",
  },
  {
    code: "NL",
    name: "Netherlands",
    dial_code: "+31",
    format: "X XX XX XX XX",
  },
  {
    code: "NC",
    name: "New Caledonia",
    dial_code: "+687",
    format: "XX XX XX",
  },
  {
    code: "NZ",
    name: "New Zealand",
    dial_code: "+64",
    format: "XXX XXX XXXX",
  },
  {
    code: "NI",
    name: "Nicaragua",
    dial_code: "+505",
    format: "XXXX XXXX",
  },
  {
    code: "NE",
    name: "Niger",
    dial_code: "+227",
    format: "XX XX XX XX",
  },
  {
    code: "NG",
    name: "Nigeria",
    dial_code: "+234",
    format: "XXX XXX XXXX",
  },
  {
    code: "NU",
    name: "Niue",
    dial_code: "+683",
    format: "XXXX",
  },
  {
    code: "NF",
    name: "Norfolk Island",
    dial_code: "+672",
    format: "XXX XXX",
  },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    dial_code: "+1670",
    format: "XXX XXXX",
  },
  {
    code: "NO",
    name: "Norway",
    dial_code: "+47",
    format: "XXX XX XXX",
  },
  {
    code: "OM",
    name: "Oman",
    dial_code: "+968",
    format: "XXXX XXXX",
  },
  {
    code: "PK",
    name: "Pakistan",
    dial_code: "+92",
    format: "XXX XXX XXXX",
  },
  {
    code: "PW",
    name: "Palau",
    dial_code: "+680",
    format: "XXX XXXX",
  },
  {
    code: "PS",
    name: "Palestine",
    dial_code: "+970",
    format: "XXX XX XXXX",
  },
  {
    code: "PA",
    name: "Panama",
    dial_code: "+507",
    format: "XXXX XXXX",
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    dial_code: "+675",
    format: "XXX XXXX",
  },
  {
    code: "PY",
    name: "Paraguay",
    dial_code: "+595",
    format: "XXX XXXXXX",
  },
  {
    code: "PE",
    name: "Peru",
    dial_code: "+51",
    format: "XXX XXX XXX",
  },
  {
    code: "PH",
    name: "Philippines",
    dial_code: "+63",
    format: "XXX XXX XXXX",
  },
  {
    code: "PL",
    name: "Poland",
    dial_code: "+48",
    format: "XXX XXX XXX",
  },
  {
    code: "PT",
    name: "Portugal",
    dial_code: "+351",
    format: "XXX XXX XXX",
  },
  {
    code: "PR",
    name: "Puerto Rico",
    dial_code: "+1",
    format: "XXX XXX XXXX",
  },
  {
    code: "QA",
    name: "Qatar",
    dial_code: "+974",
    format: "XXXX XXXX",
  },
  {
    code: "RE",
    name: "Reunion",
    dial_code: "+262",
    format: "XXX XX XX XX",
  },
  {
    code: "RO",
    name: "Romania",
    dial_code: "+40",
    format: "XXX XXX XXX",
  },
  {
    code: "RU",
    name: "Russia",
    dial_code: "+7",
    format: "XXX XXX XXXX",
  },
  {
    code: "RW",
    name: "Rwanda",
    dial_code: "+250",
    format: "XXX XXX XXX",
  },
  {
    code: "BL",
    name: "Saint Barthélemy",
    dial_code: "+590",
    format: "XXX XX XX XX",
  },
  {
    code: "SH",
    name: "Saint Helena",
    dial_code: "+290",
    format: "XXXX",
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    dial_code: "+1869",
    format: "XXX XXXX",
  },
  {
    code: "LC",
    name: "Saint Lucia",
    dial_code: "+1758",
    format: "XXX XXXX",
  },
  {
    code: "MF",
    name: "Saint Martin",
    dial_code: "+590",
    format: "XXX XX XX XX",
  },
  {
    code: "PM",
    name: "Saint Pierre and Miquelon",
    dial_code: "+508",
    format: "XX XX XX",
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    dial_code: "+1784",
    format: "XXX XXXX",
  },
  {
    code: "WS",
    name: "Samoa",
    dial_code: "+685",
    format: "XXXXXX",
  },
  {
    code: "SM",
    name: "San Marino",
    dial_code: "+378",
    format: "XXXX XXXXXX",
  },
  {
    code: "ST",
    name: "Sao Tome and Principe",
    dial_code: "+239",
    format: "XXX XXXX",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    dial_code: "+966",
    format: "XX XXX XXXX",
  },
  {
    code: "SN",
    name: "Senegal",
    dial_code: "+221",
    format: "XX XXX XX XX",
  },
  {
    code: "RS",
    name: "Serbia",
    dial_code: "+381",
    format: "XX XXX XXXX",
  },
  {
    code: "SC",
    name: "Seychelles",
    dial_code: "+248",
    format: "X XX XX XX",
  },
  {
    code: "SL",
    name: "Sierra Leone",
    dial_code: "+232",
    format: "XX XXX XXX",
  },
  {
    code: "SG",
    name: "Singapore",
    dial_code: "+65",
    format: "XXXX XXXX",
  },
  {
    code: "SK",
    name: "Slovakia",
    dial_code: "+421",
    format: "XXX XXX XXX",
  },
  {
    code: "SI",
    name: "Slovenia",
    dial_code: "+386",
    format: "XX XXX XXX",
  },
  {
    code: "SB",
    name: "Solomon Islands",
    dial_code: "+677",
    format: "XXXXX",
  },
  {
    code: "SO",
    name: "Somalia",
    dial_code: "+252",
    format: "XX XXX XXX",
  },
  {
    code: "ZA",
    name: "South Africa",
    dial_code: "+27",
    format: "XX XXX XXXX",
  },
  {
    code: "SS",
    name: "South Sudan",
    dial_code: "+211",
    format: "XX XXX XXXX",
  },
  {
    code: "ES",
    name: "Spain",
    dial_code: "+34",
    format: "XXX XXX XXX",
  },
  {
    code: "LK",
    name: "Sri Lanka",
    dial_code: "+94",
    format: "XX XXX XXXX",
  },
  {
    code: "SD",
    name: "Sudan",
    dial_code: "+249",
    format: "XX XXX XXXX",
  },
  {
    code: "SR",
    name: "Suriname",
    dial_code: "+597",
    format: "XXX XXXX",
  },
  {
    code: "SJ",
    name: "Svalbard and Jan Mayen",
    dial_code: "+47",
    format: "XXX XX XXX",
  },
  {
    code: "SZ",
    name: "Swaziland",
    dial_code: "+268",
    format: "XXXX XXXX",
  },
  {
    code: "SE",
    name: "Sweden",
    dial_code: "+46",
    format: "XX XXX XXXX",
  },
  {
    code: "CH",
    name: "Switzerland",
    dial_code: "+41",
    format: "XX XXX XXXX",
  },
  {
    code: "SY",
    name: "Syria",
    dial_code: "+963",
    format: "XXX XXX XXX",
  },
  {
    code: "TW",
    name: "Taiwan",
    dial_code: "+886",
    format: "XXX XXX XXX",
  },
  {
    code: "TJ",
    name: "Tajikistan",
    dial_code: "+992",
    format: "XX XXX XXXX",
  },
  {
    code: "TZ",
    name: "Tanzania",
    dial_code: "+255",
    format: "XXX XXX XXX",
  },
  {
    code: "TH",
    name: "Thailand",
    dial_code: "+66",
    format: "X XXXX XXXX",
  },
  {
    code: "TL",
    name: "Timor-Leste",
    dial_code: "+670",
    format: "XXXX XXXX",
  },
  {
    code: "TG",
    name: "Togo",
    dial_code: "+228",
    format: "XX XXX XXX",
  },
  {
    code: "TK",
    name: "Tokelau",
    dial_code: "+690",
    format: "XXXX",
  },
  {
    code: "TO",
    name: "Tonga",
    dial_code: "+676",
    format: "XXXXX",
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    dial_code: "+1868",
    format: "XXX XXXX",
  },
  {
    code: "TN",
    name: "Tunisia",
    dial_code: "+216",
    format: "XX XXX XXX",
  },
  {
    code: "TR",
    name: "Turkey",
    dial_code: "+90",
    format: "XXX XXX XXXX",
  },
  {
    code: "TM",
    name: "Turkmenistan",
    dial_code: "+993",
    format: "XX XXXXXX",
  },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    dial_code: "+1649",
    format: "XXX XXXX",
  },
  {
    code: "TV",
    name: "Tuvalu",
    dial_code: "+688",
    format: "XXXXX",
  },
  {
    code: "UG",
    name: "Uganda",
    dial_code: "+256",
    format: "XXX XXX XXX",
  },
  {
    code: "UA",
    name: "Ukraine",
    dial_code: "+380",
    format: "XX XXX XX XX",
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    dial_code: "+971",
    format: "XX XXX XXXX",
  },
  {
    code: "GB",
    name: "United Kingdom",
    dial_code: "+44",
    format: "XXXX XXXXXX",
  },
  {
    code: "US",
    name: "United States",
    dial_code: "+1",
    format: "XXX XXX XXXX",
  },
  {
    code: "UY",
    name: "Uruguay",
    dial_code: "+598",
    format: "X XXX XXXX",
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    dial_code: "+998",
    format: "XX XXX XXXX",
  },
  {
    code: "VU",
    name: "Vanuatu",
    dial_code: "+678",
    format: "XXXXX",
  },
  {
    code: "VE",
    name: "Venezuela",
    dial_code: "+58",
    format: "XXX XXX XXXX",
  },
  {
    code: "VN",
    name: "Vietnam",
    dial_code: "+84",
    format: "XXX XXX XXX",
  },
  {
    code: "VG",
    name: "Virgin Islands, British",
    dial_code: "+1284",
    format: "XXX XXXX",
  },
  {
    code: "VI",
    name: "Virgin Islands, U.S.",
    dial_code: "+1340",
    format: "XXX XXXX",
  },
  {
    code: "WF",
    name: "Wallis and Futuna",
    dial_code: "+681",
    format: "XX XX XX",
  },
  {
    code: "YE",
    name: "Yemen",
    dial_code: "+967",
    format: "XXX XXX XXX",
  },
  {
    code: "ZM",
    name: "Zambia",
    dial_code: "+260",
    format: "XX XXX XXXX",
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    dial_code: "+263",
    format: "XX XXX XXXX",
  },
]

export function formatPhoneNumber(phoneNumber: string, countryCode: string): string {
  // Remove all non-digit characters
  const digitsOnly = phoneNumber.replace(/\D/g, "")

  // Find the country format
  const country = countryCodes.find((c) => c.dial_code === countryCode)

  if (!country) {
    return digitsOnly
  }

  // Format based on the country's pattern
  const format = country.format
  let formattedNumber = ""
  let digitIndex = 0

  for (let i = 0; i < format.length; i++) {
    if (format[i] === "X") {
      if (digitIndex < digitsOnly.length) {
        formattedNumber += digitsOnly[digitIndex]
        digitIndex++
      }
    } else {
      if (digitIndex < digitsOnly.length) {
        formattedNumber += format[i]
      }
    }
  }

  return formattedNumber
}

export function getMaxLengthForCountry(countryCode: string): number {
  const country = countryCodes.find((c) => c.dial_code === countryCode)
  if (!country) return 11 // Default max length

  // Count the number of X's in the format string
  return (country.format.match(/X/g) || []).length
}
